/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Entities.Article;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jacqu
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
        HashMap<String,TreeMap<String, ArrayList<Article>>> mesInformations;
    
    
    DefaultMutableTreeNode racine;
    DefaultMutableTreeNode racine2;
    DefaultMutableTreeNode noeudNomPigiste;
    DefaultMutableTreeNode noeudNomMagazine;
    DefaultMutableTreeNode noeudArticle;
    DefaultMutableTreeNode noeudCA;
    DefaultTreeModel model;
    DefaultTreeModel model2;

    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblNomMag = new javax.swing.JLabel();
        lblNomPig = new javax.swing.JLabel();
        cboMagazines = new javax.swing.JComboBox<>();
        cboPigistes = new javax.swing.JComboBox<>();
        lblNomArticle = new javax.swing.JLabel();
        txtNomArticle = new javax.swing.JTextField();
        lblNbFeuillets = new javax.swing.JLabel();
        spNbFeuillets = new javax.swing.JSpinner();
        btnValider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trEditions = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        trPigistes = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        lblTitre.setText("Magazine - Pigiste - Article");

        lblNomMag.setText("Nom du magazine");

        lblNomPig.setText("Nom du pigiste");

        cboMagazines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le monde du PC", "France Football", "Renault Mag" }));

        cboPigistes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alison", "Fortin", "Garnier" }));

        lblNomArticle.setText("Nom de l'article");

        lblNbFeuillets.setText("Nombre de feuillets");

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(trEditions);

        jScrollPane3.setViewportView(trPigistes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomMag)
                                    .addComponent(lblNomPig)
                                    .addComponent(lblNomArticle)
                                    .addComponent(lblNbFeuillets))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMagazines, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboPigistes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomArticle)
                                    .addComponent(spNbFeuillets, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitre)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomMag)
                            .addComponent(cboMagazines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomPig)
                            .addComponent(cboPigistes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomArticle)
                            .addComponent(txtNomArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNbFeuillets)
                            .addComponent(spNbFeuillets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnValider))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        int feuillet = Integer.parseInt(spNbFeuillets.getValue().toString());
        String nomArticle = txtNomArticle.getText();
        String nomPigiste = cboPigistes.getSelectedItem().toString();
        String nomMagasine = cboMagazines.getSelectedItem().toString();
        // A vous de jouer
        if(txtNomArticle.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Saisir un nom d'article","Erreur de saisie",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            // On crée la tâche
            Article leArticle = new Article(txtNomArticle.getText(), feuillet);
            // On teste si le thème n'est pas présent : dans ce cas il faut tout créer !
            if (!mesInformations.containsKey(nomPigiste))
            {
                ArrayList<Article> lesArticles = new ArrayList<>();
                lesArticles.add(leArticle);
                TreeMap<String, ArrayList<Article>> lesMagazine = new TreeMap<>();
                lesMagazine.put(nomMagasine, lesArticles);
                mesInformations.put(nomPigiste, lesMagazine);
            }
            // Le thème est présent mais il faut vérifier si le projet existe
            else if (!mesInformations.get(nomPigiste).containsKey(nomMagasine)){
                ArrayList<Article> lesArticles = new ArrayList<>();
                lesArticles.add(leArticle);
                mesInformations.get(nomPigiste).put(nomMagasine, lesArticles);
            }
            else
            {
                // le projet est présent donc il y a déjà des tâches pour ce projet
                // Il suffit d'ajouter la nouvelle tâche
                mesInformations.get(nomPigiste).get(nomMagasine).add(leArticle);
            }
            RemplirEdition();
            RemplirPigiste();
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        spNbFeuillets.setModel(new SpinnerNumberModel(01,01,10,1));
        
        // A vous de jouer
        racine = new DefaultMutableTreeNode("Les éditions");
        racine2 = new DefaultMutableTreeNode("Le CA par pigiste");
        model = new DefaultTreeModel(racine);
        model2 = new DefaultTreeModel(racine2);
        trEditions.setModel(model);
        trPigistes.setModel(model2);
        mesInformations = new HashMap<>();
    }//GEN-LAST:event_formWindowOpened
        double Alison = 1.89;
        double salaireAlison = 0;
        double Fortin = 1.76;
        double salaireFortin = 0;
        double Garnier = 1.33;
        double salaireGarnier = 0;
        double salaire = 0;
    
        public void RemplirEdition()
    {
        racine.removeAllChildren();
        for (String pigiste : mesInformations.keySet())
        {
            noeudNomPigiste = new DefaultMutableTreeNode(pigiste);
            for (String magazine : mesInformations.get(pigiste).keySet())
            {
                noeudNomMagazine = new DefaultMutableTreeNode(magazine);
                for (Article unArticle : mesInformations.get(pigiste).get(magazine))
                {
                    noeudArticle = new DefaultMutableTreeNode(unArticle.getTitreArticle());
                    noeudNomMagazine.add(noeudArticle);
                    noeudArticle = new DefaultMutableTreeNode(unArticle.getNbFeuillets());
                    noeudNomMagazine.add(noeudArticle);
                }
                noeudNomPigiste.add(noeudNomMagazine);
            }
            racine.add(noeudNomPigiste);
        }
        model = new DefaultTreeModel(racine);
        trEditions.setModel(model);
        for(int i = 0 ; i < trEditions.getRowCount() ; i++)
        {
            trEditions.expandRow(i);
        }
    }

        public void RemplirPigiste()
    {
        racine2.removeAllChildren();
        for (String pigiste : mesInformations.keySet())
        {
            noeudNomPigiste = new DefaultMutableTreeNode(pigiste);
            for (String magazine : mesInformations.get(pigiste).keySet())
            {
                noeudNomMagazine = new DefaultMutableTreeNode(magazine);
                for (Article unArticle : mesInformations.get(pigiste).get(magazine))
                {
                    if(pigiste == "Alison") {
                        salaireAlison = salaireAlison + Alison*unArticle.getNbFeuillets();
                        salaire = salaireAlison;
                    }
                    else if (pigiste == "Fortin"){
                        salaireFortin = salaireFortin +  Fortin*unArticle.getNbFeuillets();
                        salaire = salaireFortin;
                    }
                    else if (pigiste == "Garnier"){
                        salaireGarnier = salaireGarnier + Garnier*unArticle.getNbFeuillets();
                        salaire = salaireGarnier;
                    }
                    noeudCA = new DefaultMutableTreeNode(pigiste+ " : " + salaire);
                }
            }
            racine2.add(noeudCA);
        }
        model2 = new DefaultTreeModel(racine2);
        trPigistes.setModel(model2);
        for(int i = 0 ; i < trPigistes.getRowCount() ; i++)
        {
            trPigistes.expandRow(i);
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox<String> cboMagazines;
    private javax.swing.JComboBox<String> cboPigistes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNbFeuillets;
    private javax.swing.JLabel lblNomArticle;
    private javax.swing.JLabel lblNomMag;
    private javax.swing.JLabel lblNomPig;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JSpinner spNbFeuillets;
    private javax.swing.JTree trEditions;
    private javax.swing.JTree trPigistes;
    private javax.swing.JTextField txtNomArticle;
    // End of variables declaration//GEN-END:variables
}
